---
title: Claire Coleman
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: claire.coleman@waikato.ac.nz
description: Copyright 2018
baseurl: ''
url: ''
facebook_username: clairecolemannz
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
